import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:hive_ce_flutter/hive_ce_flutter.dart';

import 'core/constants/app_constants.dart';
import 'models/downloaded_lecture_model.dart';
import 'app.dart';
// import 'firebase_options.dart'; // generated by `flutterfire configure` — see README

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // --- Firebase ---
  // Uncomment once you've run `flutterfire configure` (see README Day-1 setup).
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await Firebase.initializeApp();

  // Route uncaught Flutter errors to Crashlytics — set up once, forget about it.
  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;

  // --- Hive local storage ---
  await Hive.initFlutter();
  Hive.registerAdapter(DownloadedLectureAdapter());
  await Hive.openBox<DownloadedLecture>(AppConstants.downloadedLecturesBox);
  await Hive.openBox(AppConstants.appMetaBox);

  runApp(const ProviderScope(child: UlamaCircleApp()));
}
